### ISSUE TITLE
can't close keyboard from my main script

### ISSUE THREAD

**Issue by mamezito-zz** [imaaronjames/Simple-Android-Keyboards#1]
http://share.framerjs.com/xb9d7v4u2cu4/

i have complex interraction in my app, which requires closing keyboard on other button click, not only done inside the keyboard, but i can't find a way to destroy layer

**Comment by imaaronjames** [comment]
I'm out of town and not close to a computer at the moment. You should be able to target the keyboard layer directly. I will look into this as soon as I get to a computer. 
Stay tuned,
Aaron James
On Dec 28, 2015 11:05 AM, mamezito notifications@github.com wrote:http://shareframerjscom/xb9d7v4u2cu4/

i have complex interraction in my app, which requires closing keyboard on other button click, not only done inside the keyboard, but i can't find a way to destroy layer

**Comment by mamezito-zz** [comment]
got help at slack already, thanx

**Comment by imaaronjames** [comment]
Fantastic. Let me know if you need any further help. Cheers. 
On Dec 28, 2015 1:18 PM, mamezito notifications@github.com wrote:got help at slack already, thanx
